# Generated by Django 5.1.6 on 2025-02-27 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('current_role', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('preferred_industries', models.CharField(blank=True, max_length=255, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=50, null=True)),
                ('certifications', models.JSONField(blank=True, null=True)),
                ('projects', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('career_goals', models.TextField(blank=True, null=True)),
                ('learning_preferences', models.CharField(blank=True, choices=[('Self-paced', 'Self-paced'), ('Bootcamps', 'Bootcamps'), ('University courses', 'University courses')], max_length=50, null=True)),
                ('soft_skills', models.JSONField(blank=True, null=True)),
                ('work_preference', models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On-site', 'On-site')], max_length=50, null=True)),
                ('job_search_status', models.CharField(blank=True, choices=[('Open to work', 'Open to work'), ('Just exploring', 'Just exploring'), ('Actively applying', 'Actively applying')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
